defaults:
  - model: llama           
  - training: no_lora         
  - dataset: our_long_form
  - _self_

probe_config:
  probe_id: "${model.short_name}_${training.short_name}_${dataset.short_name}_layer${probe_config.layer}"
  layer: 30
  load_from: null
  hf_repo_id: "tymciurymciu/hallucination-probes"
  threshold: 0.5
  model_name: "${model.probe_config.model_name}"
  probe_dtype: auto
  normalize_before_head: none

wandb_project: "hallucination-probes"
wandb_tags: []
upload_to_hf: true
save_evaluation_metrics: true
save_roc_curves: true
dump_raw_eval_results: true
model_dtype: auto

# Shared Training hyperparameters
per_device_train_batch_size: 8 
per_device_eval_batch_size: 8
high_loss_threshold: null
anneal_max_aggr: true
anneal_warmup: 1.0
enable_gradient_checkpointing: true
gradient_accumulation_steps: 1
max_grad_norm: 1.0
logging_steps: 50
seed: 42
